version: '2'

services:
  proxy:
    image: traefik:latest
    networks:
      - webgateway
    restart: "always"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml

networks:
  webgateway:
    driver: bridge